name: CI

on: 
  workflow_dispatch:
  


jobs:
  build:
    runs-on: macOS-13
    permissions:
      id-token: write
      contents: read
    steps:
    - name: lcpu
      run: lcpu
    - uses: fly-ci/wingman-action@v1
      if: failure()
