name: CI

on: 
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: macOS-13
    strategy:
      matrix:
        xcode:
          - "15.0"
    steps:
    - name: lcpu
      run: lcpu
    - uses: fly-ci/wingman-action@v1
      if: failure()
