name: App Size Stats

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - "15.0"
    steps:
    - uses: actions/checkout@v1
    - name: uname -a
      run: uname -a
    - name: sysctl -a | grep cpu
      run: sysctl -a | grep cpu
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: bundle install
      run: bundle update --bundler && bundle install
    - name: Install CocoaPods dependencies
      run: bundle exec pod install
    - run: git config --global core.quotepath false # for Ikemen on SwiftPM
    - name: Build (iOS)
      run: |
        set -o pipefail
        xcodebuild \
          -workspace iMast.xcworkspace -scheme "iMast iOS" -destination "generic/platform=iOS" -configuration Release \
          build -derivedDataPath ./build \
          CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty -c

