name: CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-13
    strategy:
      matrix:
        xcode:
          - "15.0"
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: |
          echo "Runner Temp Directory: $RUNNER_TEMP"
          echo "Runner Tool Cache Directory: $RUNNER_TOOL_CACHE"
          echo "Runner Workspace Directory: $RUNNER_WORKSPACE"
