name: CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print Runner Dirs
      run: |
          echo "Runner Temp Directory: $RUNNER_TEMP"
          echo "Runner Tool Cache Directory: $RUNNER_TOOL_CACHE"
          echo "Runner Workspace Directory: $RUNNER_WORKSPACE"
