name: Build and Deploy with Approval

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: flyci-macos-large-latest-m1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Build
        run: echo "Build step runs here"

  deploy:
    runs-on: flyci-macos-large-latest-m1
    needs: build
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deployment step runs here"
        id: deploy

      # Optional: Set deployment URL
      - name: Set Deployment URL
        run: echo "::set-output name=deployment-url::http://example.com"
        id: set-deployment-url
